services:
  api:
    image: ghcr.io/vano04/mono:${MONO_VERSION:-0.1.6}
    build: !reset null

  mcp:
    image: ghcr.io/vano04/mono:${MONO_VERSION:-0.1.6}
    build: !reset null

  web:
    image: ghcr.io/vano04/mono-web:${MONO_VERSION:-0.1.6}
    build: !reset null
